### PR TITLE
updated layout for home page

### LINKED ISSUE #84: want to change the ui/ux of the site.
would like to change the ui/ux of the site to create a visually appealing site. So that it will be easy for the user to interact.

### PR DESCRIPTION
**Pull request by Aazib-at-hub**
## What does this PR do?
changes the layout to the home page.

Fixes #84

Screenshot from 2024-10-11 01-59-04

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ yes ] Test A
- [ ] Test B

## Mandatory Tasks

- [ yes ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Aazib-at-hub** [comment]
@rajatuiwebdev Here It is? Is this good or you need some modifications.

**Comment by Aazib-at-hub** [comment]
@rajatuiwebdev ?

**Comment by Aazib-at-hub** [comment]
@rajatuiwebdev ?

**Comment by Aazib-at-hub** [comment]
@rajatuiwebdev brother please add the labels of gssocext too

**Comment by sanjay-kv** [comment]
@rajatuiwebdev  could you add the labels?

**Pull request merged**
