### PR TITLE
fix: Added confetti on loading

### LINKED ISSUE #10: Add confetti on loading
A confetti when a user loads the website will add more to the project appeal.

### PR DESCRIPTION
**Pull request by NamanSriva**
Description 
This PR adds a confetti on loading the page. It shows falling rectangles as a confetti. It's timeout is set to 10 seconds which can be modified.

Screenshots-

Screenshot (101)

Fixes #10

### CODE REVIEW

**Comment by NamanSriva** [comment]
Hi @rajatuiwebdev,
I have added the confetti you can see the PR i also attached screenshots. If you want some other design of confetti then you can describe me I will change it.

**Comment by rajatuiwebdev** [comment]
Make a few changes, on mobile device there’s a gap from where the confetti initiates and it cuts abruptly. Fade it away or settle it down if you can. Let me know if you can do it else I will merge with how it is right now.

**Comment by NamanSriva** [comment]
Yes I can do the changes as you asked. Once completed I will push the code and inform you.

**Comment by NamanSriva** [comment]
@rajatuiwebdev changes made as you said to do(settle the confetti at bottom, margin and animation) and i also changed the color of rectangles from red to blue shade to match the color of website and also improved the design of footer as it was not visible clearly.

Note-( commented the red shade which can be used by uncommenting it)
Screenshot (103)

**Pull request merged**
