### PR TITLE
Changed to React and TailwindCSS

### LINKED ISSUE #1: Replacing the existing code with React.js with UI enhancements
We can switch to React components with Tailwind structure rather than Html and Css which is according to the current standards.

### PR DESCRIPTION
**Pull request by debianbaker**
Fixes #1 
This is the basic React structure with TailwindCSS instead of HTML and CSS. 
Extra Additions  - 
1. localStorage usages
2. Routing in react
3. Some UI enhancements

### CODE REVIEW

**Comment by debianbaker** [comment]
Hi @rajatuiwebdev, can you review?

**Comment by rajatuiwebdev** [comment]
There are some conflicting files.

**Comment by debianbaker** [comment]
Ok 👍 I'll try to resolve

**Comment by debianbaker** [comment]
I have included the index.html and styles.css both, and the react folder is separate. Conflicts are removed. 
Now deploying this react application is the part from your side. Looking forward.

**Comment by debianbaker** [comment]
@rajatuiwebdev any updates?

**Comment by debianbaker** [comment]
@rajatuiwebdev have u reviewed the pr?

**Pull request closed without merging**
