### PR TITLE
AddHeader#31

### PR DESCRIPTION
**Pull request by anshika-75**
I have added a responsive navbar that includes a logo and links for "Contact Us" and "About." Additionally, I implemented a dark and light theme toggle feature to enhance the overall appearance of the website.

These updates aim to improve user experience and accessibility, allowing users to switch between themes based on their preference.

### CODE REVIEW

**Comment by rajatuiwebdev** [comment]
Kindly do the changes on latest branch and resubmit the commit.

**Comment by rajatuiwebdev** [comment]
Kindly resolve the conflicts and update the PR.

**Comment by anshika-75** [comment]
okay i will update it

**Comment by rajatuiwebdev** [comment]
Not updated, kindly resubmit the PR when done.

**Pull request closed without merging**
